# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/adda.xdc

# Block Designs: bd/design_CPU_System/design_CPU_System.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System || ORIG_REF_NAME==design_CPU_System} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_microblaze_0_0/design_CPU_System_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_microblaze_0_0 || ORIG_REF_NAME==design_CPU_System_microblaze_0_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_dlmb_v10_1/design_CPU_System_dlmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_dlmb_v10_1 || ORIG_REF_NAME==design_CPU_System_dlmb_v10_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_ilmb_v10_1/design_CPU_System_ilmb_v10_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_ilmb_v10_1 || ORIG_REF_NAME==design_CPU_System_ilmb_v10_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_dlmb_bram_if_cntlr_1/design_CPU_System_dlmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_CPU_System_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_ilmb_bram_if_cntlr_1/design_CPU_System_ilmb_bram_if_cntlr_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==design_CPU_System_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_lmb_bram_1/design_CPU_System_lmb_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_lmb_bram_1 || ORIG_REF_NAME==design_CPU_System_lmb_bram_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_xbar_0 || ORIG_REF_NAME==design_CPU_System_xbar_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_microblaze_0_axi_periph_0/design_CPU_System_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_microblaze_0_axi_periph_0 || ORIG_REF_NAME==design_CPU_System_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_microblaze_0_axi_intc_0/design_CPU_System_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_microblaze_0_axi_intc_0 || ORIG_REF_NAME==design_CPU_System_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_microblaze_0_xlconcat_0/design_CPU_System_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_microblaze_0_xlconcat_0 || ORIG_REF_NAME==design_CPU_System_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_mdm_1_1/design_CPU_System_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_mdm_1_1 || ORIG_REF_NAME==design_CPU_System_mdm_1_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_clk_wiz_1_1/design_CPU_System_clk_wiz_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_clk_wiz_1_1 || ORIG_REF_NAME==design_CPU_System_clk_wiz_1_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_rst_clk_wiz_1_100M_1/design_CPU_System_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==design_CPU_System_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_0_0/design_CPU_System_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_uartlite_0_0 || ORIG_REF_NAME==design_CPU_System_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_gpio_0_0/design_CPU_System_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_gpio_0_0 || ORIG_REF_NAME==design_CPU_System_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_gpio_1_0/design_CPU_System_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_gpio_1_0 || ORIG_REF_NAME==design_CPU_System_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_uartlite_1_0/design_CPU_System_axi_uartlite_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_uartlite_1_0 || ORIG_REF_NAME==design_CPU_System_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_quad_spi_0_0/design_CPU_System_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_quad_spi_0_0 || ORIG_REF_NAME==design_CPU_System_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_gpio_2_0/design_CPU_System_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_gpio_2_0 || ORIG_REF_NAME==design_CPU_System_axi_gpio_2_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_axi_timer_0_0/design_CPU_System_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_axi_timer_0_0 || ORIG_REF_NAME==design_CPU_System_axi_timer_0_0} -quiet] -quiet

# IP: bd/design_CPU_System/ip/design_CPU_System_auto_pc_0/design_CPU_System_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_CPU_System_auto_pc_0 || ORIG_REF_NAME==design_CPU_System_auto_pc_0} -quiet] -quiet

# XDC: d:/3/IO/IO.gen/sources_1/bd/design_CPU_System/design_CPU_System_ooc.xdc
