# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/3/IO/IO.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0.xci
# IP: The module: 'design_CPU_System_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/3/IO/IO.gen/sources_1/bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/3/IO/IO.srcs/sources_1/bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0.xci
# IP: The module: 'design_CPU_System_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/3/IO/IO.gen/sources_1/bd/design_CPU_System/ip/design_CPU_System_xbar_0/design_CPU_System_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_CPU_System_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
